services:
    postgres:
      image: postgres:13
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: db
        POSTGRES_SCHEMA: asd
      volumes:
        - ./scripts:/docker-entrypoint-initdb.d
        - postgres-db-volume:/var/lib/postgresql/data
      healthcheck:
        test: ["CMD", "pg_isready", "-U", "postgres"]
        interval: 5s
        retries: 5
      ports:
      - 5432:5432
      restart: always

volumes:
  postgres-db-volume: